# Generated by Django 4.2.18 on 2025-02-10 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Grupo de usuarios')),
            ],
            options={
                'verbose_name': 'Menú',
                'verbose_name_plural': 'Menús',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_link', models.CharField(max_length=255, verbose_name='Texto del enlace')),
                ('url', models.CharField(max_length=250, verbose_name='URL')),
                ('icon', models.CharField(max_length=100, verbose_name='Ícono')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='configuration.menu', verbose_name='Menú')),
            ],
            options={
                'verbose_name': 'Ítem de Menú',
                'verbose_name_plural': 'Ítems de Menú',
            },
        ),
    ]
