# Generated by Django 4.2.18 on 2025-01-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('NIE', models.CharField(max_length=15, verbose_name='NIE')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
            ],
        ),
    ]
